name: polya_github
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - ipykernel=6.29.5
  - matplotlib=3.9.4
  - numpy=1.26
  - pandas=2.2.3
  - pyfaidx=0.8.1.4
  - scipy
  - tqdm
  - pip
  - pip:
      - Markdown==3.9
      - MarkupSafe==3.0.2
      - Werkzeug==3.1.3
      - astunparse==1.6.3
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - idna==3.10
      - isolearn==0.2.1
      - libclang==18.1.1
      - opt_einsum==3.4.0
      - protobuf==5.29.5
      - requests==2.32.5
      - six==1.17.0
      - tensorboard==2.19.0
      - tensorflow==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - urllib3==2.5.0
      - wrapt==1.17.3
